#!/bin/bash
# oh-my-openclaw setup script
# Installs oh-my-openclaw as an OpenClaw skill

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_NAME="oh-my-openclaw"

# Detect OpenClaw workspace
if [ -d "$HOME/.openclaw/workspace" ]; then
    WORKSPACE="$HOME/.openclaw/workspace"
elif [ -n "$OPENCLAW_WORKSPACE" ]; then
    WORKSPACE="$OPENCLAW_WORKSPACE"
else
    echo "❌ OpenClaw workspace not found."
    echo "   Expected: ~/.openclaw/workspace"
    echo "   Or set OPENCLAW_WORKSPACE environment variable."
    exit 1
fi

echo "🔧 oh-my-openclaw Setup"
echo "========================"
echo ""
echo "Source: $SCRIPT_DIR"
echo "Target: $WORKSPACE/skills/$SKILL_NAME"
echo ""

# Create skills directory if needed
mkdir -p "$WORKSPACE/skills"

# Check if already installed
if [ -L "$WORKSPACE/skills/$SKILL_NAME" ]; then
    EXISTING_TARGET=$(readlink -f "$WORKSPACE/skills/$SKILL_NAME")
    if [ "$EXISTING_TARGET" = "$SCRIPT_DIR" ]; then
        echo "✅ Already installed (symlink exists)."
    else
        echo "⚠️  Existing symlink points to: $EXISTING_TARGET"
        echo "   Updating to: $SCRIPT_DIR"
        rm "$WORKSPACE/skills/$SKILL_NAME"
        ln -s "$SCRIPT_DIR" "$WORKSPACE/skills/$SKILL_NAME"
        echo "✅ Symlink updated."
    fi
elif [ -d "$WORKSPACE/skills/$SKILL_NAME" ]; then
    echo "⚠️  Directory already exists at target. Skipping."
    echo "   Remove it first: rm -rf $WORKSPACE/skills/$SKILL_NAME"
    exit 1
else
    ln -s "$SCRIPT_DIR" "$WORKSPACE/skills/$SKILL_NAME"
    echo "✅ Symlink created."
fi

# Initialize notepad structure
echo ""
echo "📝 Initializing notepad structure..."
mkdir -p "$WORKSPACE/notepads"
mkdir -p "$WORKSPACE/plans"

for file in learnings.md decisions.md issues.md preferences.md; do
    if [ ! -f "$WORKSPACE/notepads/$file" ]; then
        echo "# ${file%.md}" > "$WORKSPACE/notepads/$file"
        echo "" >> "$WORKSPACE/notepads/$file"
        echo "<!-- Auto-generated by oh-my-openclaw. Append entries below. -->" >> "$WORKSPACE/notepads/$file"
        echo "   Created: notepads/$file"
    else
        echo "   Exists:  notepads/$file"
    fi
done

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Available commands:"
echo "  /ultrawork [task]  - Full automation (plan → execute → verify)"
echo "  /plan [task]       - Create a plan only"
echo "  /start-work        - Execute an existing plan"
echo ""
echo "Skills included:"
echo "  - git-master       - Atomic commits, rebase surgery"
echo "  - frontend-ui-ux   - Design-first UI development"
echo "  - comment-checker   - Anti-AI-slop code quality"
echo ""
echo "Tip: Ask your agent to 'read the oh-my-openclaw skill' to get started."
