#!/bin/bash
# oh-my-openclaw setup script
# Installs oh-my-openclaw as an OpenClaw skill

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_NAME="oh-my-openclaw"

# Detect OpenClaw skills directory
# Precedence: workspace/skills > ~/.openclaw/skills > $OPENCLAW_WORKSPACE/skills
if [ -n "$OPENCLAW_WORKSPACE" ] && [ -d "$OPENCLAW_WORKSPACE" ]; then
    SKILLS_DIR="$OPENCLAW_WORKSPACE/skills"
elif [ -d "$HOME/.openclaw" ]; then
    SKILLS_DIR="$HOME/.openclaw/skills"
else
    echo "❌ OpenClaw directory not found."
    echo "   Expected: ~/.openclaw/"
    echo "   Or set OPENCLAW_WORKSPACE environment variable."
    exit 1
fi

# Workspace for notepads/plans (default to project-local)
WORKSPACE="${OPENCLAW_WORKSPACE:-$(pwd)}"

echo "🔧 oh-my-openclaw Setup"
echo "========================"
echo ""
echo "Source: $SCRIPT_DIR"
echo "Target: $SKILLS_DIR/$SKILL_NAME"
echo ""

# Create skills directory if needed
mkdir -p "$SKILLS_DIR"

# Resolve real path (macOS + Linux compatible)
resolve_path() {
    if command -v realpath &>/dev/null; then
        realpath "$1"
    elif command -v greadlink &>/dev/null; then
        greadlink -f "$1"
    elif readlink -f / &>/dev/null 2>&1; then
        readlink -f "$1"
    else
        # Fallback: Python
        python3 -c "import os; print(os.path.realpath('$1'))"
    fi
}

# Check if already installed
if [ -L "$SKILLS_DIR/$SKILL_NAME" ]; then
    EXISTING_TARGET=$(resolve_path "$SKILLS_DIR/$SKILL_NAME")
    EXPECTED_TARGET=$(resolve_path "$SCRIPT_DIR")
    if [ "$EXISTING_TARGET" = "$EXPECTED_TARGET" ]; then
        echo "✅ Already installed (symlink exists)."
    else
        echo "⚠️  Existing symlink points to: $EXISTING_TARGET"
        echo "   Updating to: $SCRIPT_DIR"
        rm "$SKILLS_DIR/$SKILL_NAME"
        ln -s "$SCRIPT_DIR" "$SKILLS_DIR/$SKILL_NAME"
        echo "✅ Symlink updated."
    fi
elif [ -d "$SKILLS_DIR/$SKILL_NAME" ]; then
    echo "⚠️  Directory already exists at target. Skipping."
    echo "   Remove it first: rm -rf $SKILLS_DIR/$SKILL_NAME"
    exit 1
else
    ln -s "$SCRIPT_DIR" "$SKILLS_DIR/$SKILL_NAME"
    echo "✅ Symlink created."
fi

# Initialize notepad structure
echo ""
echo "📝 Initializing notepad structure..."
mkdir -p "$WORKSPACE/workspace/notepads"
mkdir -p "$WORKSPACE/workspace/plans"

for file in learnings.md decisions.md issues.md preferences.md; do
    if [ ! -f "$WORKSPACE/workspace/notepads/$file" ]; then
        echo "# ${file%.md}" > "$WORKSPACE/workspace/notepads/$file"
        echo "" >> "$WORKSPACE/workspace/notepads/$file"
        echo "<!-- Auto-generated by oh-my-openclaw. Append entries below. -->" >> "$WORKSPACE/workspace/notepads/$file"
        echo "   Created: workspace/notepads/$file"
    else
        echo "   Exists:  workspace/notepads/$file"
    fi
done

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Available commands:"
echo "  /ultrawork [task]  - Full automation (plan → execute → verify)"
echo "  /plan [task]       - Create a plan only"
echo "  /start-work        - Execute an existing plan"
echo ""
echo "Skills included:"
echo "  - git-master       - Atomic commits, rebase surgery"
echo "  - frontend-ui-ux   - Design-first UI development"
echo "  - comment-checker   - Anti-AI-slop code quality"
echo ""
echo "Tip: Ask your agent to 'read the oh-my-openclaw skill' to get started."
